### PR TITLE
Camera and Prima Drivers from Official Stock KitKat Kernel (LGE975_LGE977_LGE987_G_Android_Kitkat_V20a_Kernel)

### PR DESCRIPTION
**Pull request by alchemicas**
I've ported these two drivers and they are working without any issue, stock-kk camera drivers have better image quality, stock-kk prima drivers finally make Wi-Fi work decently compared to the actual drivers, where the phone loses connectivity each 2 seconds and the download/upload speeds are awfully slow.

New Prima Drivers also need updated configuration files (they obviously need the ones from stock kitkat), i've uploaded them here : http://www.mediafire.com/download/qe92ppiikd1jd9k/Stock-KK_Prima_Drivers.zip

I hope you will merge at least one of these updated drivers.

### CODE REVIEW

**Comment by alchemicas** [comment]
I forgot to say that the commits I'm talking about are :

Stock-KK Camera Drivers (0bae19bce4f1a39e6cbecd9a584840964daab5e5)
Stock-KK Prima Drivers (5b4eb46bedb351037ee13e514bf8db3904785dbc)

Other commits are not important or unstable for an official kernel.

**Comment by xyyx** [comment]
Stock-KK Camera Drivers ported by faust93 not by you. It's useless without edits in the vendors and the device tree.
Stock-KK Prima Drivers. I don't know why you do this. You can update gproj prima drivers to new version and all works ok.

**Comment by alchemicas** [comment]
Oh, that's fine, I still hope that you will rebase the whole kernel over v20a sources, because the one from jelly bean even with all your updates and optimizations is starting to get old.

**Comment by alchemicas** [comment]
Thanks for reading this and giving me your answer :)
(I mistakenly pressed the comment button before, sorry for the double comment)

**Pull request closed without merging**
